# -*- coding: utf-8 -*-
"""
Created on Sun Mar 10 03:42:57 2019

@author: pengu
"""

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
#list of fib up to 4 million
def fib():
    result = [1,2]
    while True:
        length = len(result)
        new = result[length-2]+result[length-1]
        if new>4000000:
            print(result)
            print(len(result))
            return result
        result.append(new)
        
#sum even fibbs
def sumfib(list):
    length = len(list)
    total = 0
    for i in range(1,length,3):
        total += list[i]
    print(total)
    return total

sumfib(fib())